### ISSUE TITLE
Broken DAG

### ISSUE THREAD

**Issue by mezianeAITE** [wprazuch/Astral#32]
Hi,
First of all thanks for this app you've created.

I'im trying to install Astral on linux.
I ran the command 'sudo docker-compose up' after setting the correct path in docker-compose.yml

The webserver is available on http://localhost:8080/admin/
But i have some errors on the top of the GUI:
 Broken DAG: [/app/astrowaves/airflow/dags/segment_waves.py] name 't5' is not defined 
Broken DAG: [/app/astrowaves/airflow/dags/extract_waves.py] name 't1' is not defined 

In the DAG list i only have:
0_preprocess_czi and 3_find_neighbours 
![Astral_error](https://user-images.githubusercontent.com/24890670/126333596-41b0e1d1-7cf2-4fe4-afc0-6df16f673079.png)

Do you have an idea why i have this error ?
Thanks a lot
Kind regards
Meziane AITE

**Comment by wprazuch** [comment]
Hi!
This is most probably an issue that I have not yet resolved. Have you provided some input data to the "data" folder already?
